# Generated by Django 3.1 on 2020-11-30 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('auc_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('no_of_cars', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=12)),
                ('year_founded', models.IntegerField()),
                ('revenue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('vehicle_preference', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=40)),
                ('no_of_doors', models.IntegerField()),
                ('mpg', models.FloatField()),
                ('car_availabilty', models.IntegerField()),
                ('seating_capacity', models.IntegerField()),
                ('vehicle_type', models.CharField(max_length=10)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('plate_no', models.CharField(max_length=8)),
                ('no_of_accidents', models.IntegerField(default=0)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=8)),
                ('base_price', models.FloatField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.manufacturers')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.person')),
            ],
        ),
        migrations.CreateModel(
            name='Auction_Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auction')),
                ('pers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.person')),
            ],
        ),
    ]
