# Generated by Django 3.1.4 on 2020-12-09 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20201208_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_person',
            name='auct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.auction'),
        ),
        migrations.AlterField(
            model_name='auction_person',
            name='pers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.person'),
        ),
    ]
