# Generated by Django 3.1.4 on 2020-12-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20201209_1648'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auction',
            index=models.Index(fields=['auc_date', 'start_time'], name='date_time'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['model_name'], name='mod_name'),
        ),
    ]
