# Generated by Django 3.1.4 on 2020-12-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20201209_2147'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cars',
            index=models.Index(fields=['manufacturer_id', 'model'], name='Car_Model'),
        ),
    ]
